### ISSUE TITLE
Main thread blocked upon reloading torrents.

### ISSUE THREAD

**Issue by reggian** [selim-mustafaev/TransmissionRemote#1]
Every time the torrents get reloaded there is a main thread block.
It renders the app unusable (tested with 350 files or so).

I have traced down the the blocking line to be the WagnerFischer diff.
https://github.com/selim-mustafaev/TransmissionRemote/blob/fb46e90ed0ed46c031fcfef649a719901e22a91a/TransmissionRemote/Extensions/Collections/ArrayDataProvider.swift#L90

I have not had a chance to do a deep dive into the architecture of the project. But I figure the app would benefit from filtering being handled on the background queue.

**Comment by selim-mustafaev** [comment]
Thanks for reporting, I haven't tested this client with that much torrents.

I think, it would not be the right decision to just "hide" the problem to background thread. First it would be better to understand what is wrong.

I did some profiling, and for my setup (mac mini 2018) diff is taking about 50 milliseconds to process 80 torrents. And that is too much according to DeepDiff's documentation (they advertize 45 ms for 2000 items). I'll try investigate that when I have free time. My guess right now, is that it caused by slow hash calculation for massive Torrent model.

**Comment by selim-mustafaev** [comment]
It took a long time, but finally I fixed it (I hope 😄). Project was migrated from DeepDiff to DifferenceKit, which is considerably faster, and should handle large amount of torrents much better. All changes are now in new build (v1.1.1)

**Comment by reggian** [comment]
I can confirm it is better, but with 300+ files it is still a bit glitchy.
